### PR TITLE
Get Latest Chromedriver based on LATEST_RELEASE file

### PR DESCRIPTION
**Pull request by rkavalap**

### CODE REVIEW

**Comment by imurchie** [comment]
I'm not sure that defaulting to a version that hasn't been tested with the system is the best thing. I understand wanting to upgrade, but I would rather default to a known version, and allow for use of `LATEST`, but in a way that requires explicit intervention from the user (i.e., they need to specify `LATEST`, so that it is a known act that they are responsible for, rather than a passive act that we are responsible for).

**Comment by rkavalap** [comment]
agreed. Ill make the changes based on your comments.

**Comment by jlipps** [comment]
@rkavalap i've already got the newer chromedriver in a branch. the bigger issue is that something seems to have broken in a third party dependency and our tests are not passing.

**Comment by rkavalap** [comment]
@jlipps Yes I am aware of the test failures. I didn't get a chance to track down the actual cause. 
But my intention was to have the latest version of chromedriver binary without any code change. 
I have submitted a similar PR on node-chromedriver repo as well. My original commit was to have default as LATEST, rather than to make a commit every ~6 weeks for a new version of chromedriver. Based on @imurchie comment's it made more sense to have a LKG, but give the ability to the user to have an option to download the latest chromedriver binary. 
I made similar changes on both repo's to have a LKG version as default instead of LATEST.

**Comment by rkavalap** [comment]
Squashed all commits to a single commit.

**Comment by imurchie** [comment]
@rkavalap Thanks for all the good work on this. I've updated things so the tests run and we get 2.24 as the default. It would be great to get this change in, too! 

Can you rebase with master and fix any conflicts? Then re-push to here and we'll get the ball rolling?

Thanks!

**Comment by imurchie** [comment]
I forgot to mention that you should, after rebasing, update the dependencies (`rm -rf node_modules && npm install`).

**Comment by rkavalap** [comment]
@imurchie Done !

**Comment by imurchie** [comment]
Awesome! Thanks for this!

**Comment by imurchie** [comment]
Published in `appium-chromedriver@2.9.3`.

**Pull request merged**
