### PR TITLE
feat: Add support of the new chromedriver storage

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
https://github.com/appium/appium/issues/18897

Note that we still need to support the old storage to be able to also fetch chromedrivers for older versions as the new API only contains drivers starting from the major version 114

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Can we drop the debug log of https://github.com/appium/appium-chromedriver/blob/ddc7ccf444e6d79866ebdcd511fa8cf26e30eedf/lib/chromedriver.js#L351-L353 ?

The below log had around 13500 lines in total. It was quit huge as a debug log as well... 

```
[ChromedriverGoogleapisStorageClient] The total count of entries in the mapping: 546
[ChromedriverChromelabsStorageClient] The total count of entries in the mapping: 680
[debug] [Chromedriver@361a] Got chromedrivers mapping from the storage: {
[debug] [Chromedriver@361a]   "100.0.4896.20/chromedriver_linux64.zip": {
[debug] [Chromedriver@361a]     "url": "https://chromedriver.storage.googleapis.com/100.0.4896.20/chromedriver_linux64.zip",
[debug] [Chromedriver@361a]     "etag": "d7604df0340573318e05672c2d7efaee",
[debug] [Chromedriver@361a]     "version": "100.0.4896.20",
...
[debug] [Chromedriver@361a]       "name": "win",
[debug] [Chromedriver@361a]       "arch": "64",
[debug] [Chromedriver@361a]       "cpu": "intel"
[debug] [Chromedriver@361a]     }
[debug] [Chromedriver@361a]   }
[debug] [Chromedriver@361a] }
[debug] [ChromedriverStorageClient] Selecting chromedrivers whose minimum supported browser version matches to 92
[debug] [ChromedriverStorageClient] Got 8 items

```

**Comment by KazuCocoa** [comment]
I also wondered if we could limit the number of chromedrivers to download up to 5 or around instead of all of them

```
[debug] [ChromedriverStorageClient] Will select candidate drivers versioned as '115.0.5763.0,115.0.5765.0,115.0.5767.0,115.0.5768.0,115.0.5769.0,115.0.5770.0,115.0.5771.0,115.0.5772.0,115.0.5773.0,115.0.5773.4,115.0.5776.0,115.0.5777.0,115.0.5781.0,115.0.5785.0,115.0.5789.0,115.0.5790.3,115.0.5790.13,115.0.5790.24,115.0.5790.56,115.0.5790.75,115.0.5790.90,115.0.5790.98,115.0.5790.102'
[debug] [ChromedriverStorageClient] Selecting chromedrivers whose platform matches to mac:arm64
[debug] [ChromedriverStorageClient] Got 23 items
[debug] [ChromedriverStorageClient] Got 23 drivers to sync: [
[debug] [ChromedriverStorageClient]   "115.0.5763.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5765.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5767.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5768.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5769.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5770.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5771.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5772.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5773.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5773.4/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5776.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5777.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5781.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5785.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5789.0/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5790.3/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5790.13/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5790.24/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5790.56/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5790.75/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5790.90/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5790.98/chromedriver-mac-arm64.zip",
[debug] [ChromedriverStorageClient]   "115.0.5790.102/chromedriver-mac-arm64.zip"
[debug] [ChromedriverStorageClient] ]
```

**Comment by mykola-mokhnach** [comment]
> Got chromedrivers mapping from the storage

I have truncated it

**Comment by mykola-mokhnach** [comment]
> I also wondered if we could limit the number of chromedrivers to download up to 2 or around from the latest one instead of all of them since we always use the latest one, basically,
> 
> ```
> [debug] [ChromedriverStorageClient] Will select candidate drivers versioned as '115.0.5763.0,115.0.5765.0,115.0.5767.0,115.0.5768.0,115.0.5769.0,115.0.5770.0,115.0.5771.0,115.0.5772.0,115.0.5773.0,115.0.5773.4,115.0.5776.0,115.0.5777.0,115.0.5781.0,115.0.5785.0,115.0.5789.0,115.0.5790.3,115.0.5790.13,115.0.5790.24,115.0.5790.56,115.0.5790.75,115.0.5790.90,115.0.5790.98,115.0.5790.102'
> [debug] [ChromedriverStorageClient] Selecting chromedrivers whose platform matches to mac:arm64
> [debug] [ChromedriverStorageClient] Got 23 items
> [debug] [ChromedriverStorageClient] Got 23 drivers to sync: [
> [debug] [ChromedriverStorageClient]   "115.0.5763.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5765.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5767.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5768.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5769.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5770.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5771.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5772.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5773.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5773.4/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5776.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5777.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5781.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5785.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5789.0/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5790.3/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5790.13/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5790.24/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5790.56/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5790.75/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5790.90/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5790.98/chromedriver-mac-arm64.zip",
> [debug] [ChromedriverStorageClient]   "115.0.5790.102/chromedriver-mac-arm64.zip"
> [debug] [ChromedriverStorageClient] ]
> ```

Added the code to filter out older patches

**Review by KazuCocoa — APPROVED** [review]
lgtm, thank you for the quick implementation

**Pull request merged**
